[project]
name = "youcast"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "humanize>=4.13.0",
    "streamlit>=1.49.1",
    "yt-dlp>=2025.9.5",
]
